### ISSUE TITLE
Ravenna PCB Issue

### ISSUE THREAD

**Issue by Mahfouz-z** [efabless/ravenna#1]
- The Foot Print for the tactile switch is missing a fifth ground pad. https://eu.mouser.com/ProductDetail/E-Switch/TL6330AF200Q?qs=sGAEpiMZZMsgGjVA3toVBKCPvIjROCDkCTtvIRblThM%3D
- There are some DRC errors for courtyards overlap.
![image](https://user-images.githubusercontent.com/43938352/77247246-d4f44200-6c37-11ea-9775-3639fb847adc.png)

**Comment by jeffdi** [comment]
reolved.  thanks.

**Comment by jeffdi** [comment]
resolved
